CREATE DATABASE IF NOT EXISTS PORTFOLIO_DE;
CREATE SCHEMA IF NOT EXISTS PORTFOLIO_DE.RAW_SALESFORCE;
CREATE SCHEMA IF NOT EXISTS PORTFOLIO_DE.STAGING;
CREATE SCHEMA IF NOT EXISTS PORTFOLIO_DE.CURATED;
CREATE SCHEMA IF NOT EXISTS PORTFOLIO_DE.CONTROL;

CREATE WAREHOUSE IF NOT EXISTS DE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE TABLE IF NOT EXISTS PORTFOLIO_DE.RAW_SALESFORCE.ACCOUNT_RAW (
  ID STRING,
  NAME STRING,
  INDUSTRY STRING,
  BILLINGCOUNTRY STRING,
  ANNUALREVENUE NUMBER(18,2),
  CREATEDDATE TIMESTAMP_TZ,
  LASTMODIFIEDDATE TIMESTAMP_TZ,
  SYSTEMMODSTAMP TIMESTAMP_TZ,
  _SOURCE_OBJECT STRING,
  _BUSINESS_KEY STRING,
  _EXTRACTED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS PORTFOLIO_DE.RAW_SALESFORCE.CONTACT_RAW (
  ID STRING,
  ACCOUNTID STRING,
  FIRSTNAME STRING,
  LASTNAME STRING,
  EMAIL STRING,
  TITLE STRING,
  CREATEDDATE TIMESTAMP_TZ,
  LASTMODIFIEDDATE TIMESTAMP_TZ,
  SYSTEMMODSTAMP TIMESTAMP_TZ,
  _SOURCE_OBJECT STRING,
  _BUSINESS_KEY STRING,
  _EXTRACTED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS PORTFOLIO_DE.RAW_SALESFORCE.OPPORTUNITY_RAW (
  ID STRING,
  ACCOUNTID STRING,
  NAME STRING,
  STAGENAME STRING,
  AMOUNT NUMBER(18,2),
  PROBABILITY NUMBER(5,2),
  CLOSEDATE DATE,
  ISCLOSED BOOLEAN,
  ISWON BOOLEAN,
  CREATEDDATE TIMESTAMP_TZ,
  LASTMODIFIEDDATE TIMESTAMP_TZ,
  SYSTEMMODSTAMP TIMESTAMP_TZ,
  _SOURCE_OBJECT STRING,
  _BUSINESS_KEY STRING,
  _EXTRACTED_AT TIMESTAMP_TZ
);
