CREATE OR REPLACE VIEW PORTFOLIO_DE.STAGING.ACCOUNT_DEDUP AS
SELECT *
FROM PORTFOLIO_DE.RAW_SALESFORCE.ACCOUNT_RAW
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY ID
  ORDER BY SYSTEMMODSTAMP DESC, _EXTRACTED_AT DESC
) = 1;

CREATE OR REPLACE VIEW PORTFOLIO_DE.STAGING.CONTACT_DEDUP AS
SELECT *
FROM PORTFOLIO_DE.RAW_SALESFORCE.CONTACT_RAW
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY ID
  ORDER BY SYSTEMMODSTAMP DESC, _EXTRACTED_AT DESC
) = 1;

CREATE OR REPLACE VIEW PORTFOLIO_DE.STAGING.OPPORTUNITY_DEDUP AS
SELECT *
FROM PORTFOLIO_DE.RAW_SALESFORCE.OPPORTUNITY_RAW
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY ID
  ORDER BY SYSTEMMODSTAMP DESC, _EXTRACTED_AT DESC
) = 1;

CREATE OR REPLACE VIEW PORTFOLIO_DE.STAGING.OPPORTUNITY_ENRICHED AS
SELECT
  o.ID AS OPPORTUNITY_ID,
  o.ACCOUNTID AS ACCOUNT_ID,
  a.NAME AS ACCOUNT_NAME,
  a.INDUSTRY,
  a.BILLINGCOUNTRY,
  o.NAME AS OPPORTUNITY_NAME,
  o.STAGENAME,
  o.AMOUNT,
  o.PROBABILITY,
  o.CLOSEDATE,
  o.ISCLOSED,
  o.ISWON,
  o.SYSTEMMODSTAMP
FROM PORTFOLIO_DE.STAGING.OPPORTUNITY_DEDUP o
LEFT JOIN PORTFOLIO_DE.STAGING.ACCOUNT_DEDUP a
  ON o.ACCOUNTID = a.ID;
