CREATE TABLE IF NOT EXISTS PORTFOLIO_DE.CURATED.DIM_ACCOUNT (
  ACCOUNT_ID STRING PRIMARY KEY,
  ACCOUNT_NAME STRING,
  INDUSTRY STRING,
  BILLING_COUNTRY STRING,
  ANNUAL_REVENUE NUMBER(18,2),
  LAST_SOURCE_UPDATE TIMESTAMP_TZ,
  DW_UPDATED_AT TIMESTAMP_TZ
);

MERGE INTO PORTFOLIO_DE.CURATED.DIM_ACCOUNT tgt
USING PORTFOLIO_DE.STAGING.ACCOUNT_DEDUP src
ON tgt.ACCOUNT_ID = src.ID
WHEN MATCHED AND src.SYSTEMMODSTAMP > tgt.LAST_SOURCE_UPDATE THEN UPDATE SET
  ACCOUNT_NAME = src.NAME,
  INDUSTRY = src.INDUSTRY,
  BILLING_COUNTRY = src.BILLINGCOUNTRY,
  ANNUAL_REVENUE = src.ANNUALREVENUE,
  LAST_SOURCE_UPDATE = src.SYSTEMMODSTAMP,
  DW_UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  ACCOUNT_ID, ACCOUNT_NAME, INDUSTRY, BILLING_COUNTRY,
  ANNUAL_REVENUE, LAST_SOURCE_UPDATE, DW_UPDATED_AT
) VALUES (
  src.ID, src.NAME, src.INDUSTRY, src.BILLINGCOUNTRY,
  src.ANNUALREVENUE, src.SYSTEMMODSTAMP, CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PORTFOLIO_DE.CURATED.FACT_OPPORTUNITY AS
SELECT
  OPPORTUNITY_ID,
  ACCOUNT_ID,
  OPPORTUNITY_NAME,
  STAGENAME,
  AMOUNT,
  PROBABILITY,
  AMOUNT * (PROBABILITY / 100.0) AS WEIGHTED_PIPELINE_AMOUNT,
  CLOSEDATE,
  ISCLOSED,
  ISWON,
  SYSTEMMODSTAMP AS LAST_SOURCE_UPDATE
FROM PORTFOLIO_DE.STAGING.OPPORTUNITY_ENRICHED;

CREATE OR REPLACE VIEW PORTFOLIO_DE.CURATED.CUSTOMER_360 AS
SELECT
  a.ACCOUNT_ID,
  a.ACCOUNT_NAME,
  a.INDUSTRY,
  a.BILLING_COUNTRY,
  a.ANNUAL_REVENUE,
  COUNT(DISTINCT c.ID) AS CONTACT_COUNT,
  COUNT(DISTINCT o.OPPORTUNITY_ID) AS OPPORTUNITY_COUNT,
  COALESCE(SUM(IFF(o.ISCLOSED = FALSE, o.AMOUNT, 0)), 0) AS OPEN_PIPELINE_AMOUNT,
  COALESCE(SUM(IFF(o.ISWON = TRUE, o.AMOUNT, 0)), 0) AS WON_REVENUE_AMOUNT,
  MAX(o.CLOSEDATE) AS LATEST_CLOSE_DATE
FROM PORTFOLIO_DE.CURATED.DIM_ACCOUNT a
LEFT JOIN PORTFOLIO_DE.STAGING.CONTACT_DEDUP c
  ON a.ACCOUNT_ID = c.ACCOUNTID
LEFT JOIN PORTFOLIO_DE.CURATED.FACT_OPPORTUNITY o
  ON a.ACCOUNT_ID = o.ACCOUNT_ID
GROUP BY 1,2,3,4,5;
