CREATE TABLE IF NOT EXISTS PORTFOLIO_DE.CONTROL.QUALITY_RESULTS (
  RUN_AT TIMESTAMP_TZ,
  CHECK_NAME STRING,
  STATUS STRING,
  FAILED_COUNT NUMBER,
  DETAIL STRING
);

INSERT INTO PORTFOLIO_DE.CONTROL.QUALITY_RESULTS
SELECT CURRENT_TIMESTAMP(), 'account_primary_key_not_null',
       IFF(COUNT_IF(ID IS NULL) = 0, 'PASS', 'FAIL'),
       COUNT_IF(ID IS NULL),
       'Salesforce Account Id must be populated'
FROM PORTFOLIO_DE.STAGING.ACCOUNT_DEDUP;

INSERT INTO PORTFOLIO_DE.CONTROL.QUALITY_RESULTS
SELECT CURRENT_TIMESTAMP(), 'opportunity_account_referential_integrity',
       IFF(COUNT(*) = 0, 'PASS', 'FAIL'),
       COUNT(*),
       'Opportunity AccountId must resolve to an Account'
FROM PORTFOLIO_DE.STAGING.OPPORTUNITY_DEDUP o
LEFT JOIN PORTFOLIO_DE.STAGING.ACCOUNT_DEDUP a
  ON o.ACCOUNTID = a.ID
WHERE o.ACCOUNTID IS NOT NULL
  AND a.ID IS NULL;

INSERT INTO PORTFOLIO_DE.CONTROL.QUALITY_RESULTS
SELECT CURRENT_TIMESTAMP(), 'opportunity_amount_non_negative',
       IFF(COUNT_IF(AMOUNT < 0) = 0, 'PASS', 'FAIL'),
       COUNT_IF(AMOUNT < 0),
       'Opportunity amount cannot be negative'
FROM PORTFOLIO_DE.STAGING.OPPORTUNITY_DEDUP;

INSERT INTO PORTFOLIO_DE.CONTROL.QUALITY_RESULTS
SELECT CURRENT_TIMESTAMP(), 'raw_vs_canonical_account_variance',
       IFF(
         ABS(
           (SELECT COUNT(DISTINCT ID) FROM PORTFOLIO_DE.RAW_SALESFORCE.ACCOUNT_RAW)
           - (SELECT COUNT(*) FROM PORTFOLIO_DE.STAGING.ACCOUNT_DEDUP)
         ) = 0,
         'PASS', 'FAIL'
       ),
       ABS(
         (SELECT COUNT(DISTINCT ID) FROM PORTFOLIO_DE.RAW_SALESFORCE.ACCOUNT_RAW)
         - (SELECT COUNT(*) FROM PORTFOLIO_DE.STAGING.ACCOUNT_DEDUP)
       ),
       'Distinct raw Accounts should reconcile to canonical Accounts';

SELECT *
FROM PORTFOLIO_DE.CONTROL.QUALITY_RESULTS
WHERE RUN_AT >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
ORDER BY RUN_AT DESC;
